name: Sync to GitLab

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manually trigger the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set remote repository
        env: # Retrieve env variable from GitHub secrets
          gitlab_url: ${{ secrets.TARGET_URL }}
          gitlab_username: ${{ secrets.TARGET_USERNAME }}
          gitlab_token: ${{ secrets.TARGET_TOKEN }}
        run: |
          git remote add gitlab https://${gitlab_username}:${gitlab_token}@${gitlab_url#https://}

      - name: Push to GitLab
        run: |
          git push -f --all gitlab
          git push -f --tags gitlab

      - name: Cleanup
        run: |
          git remote remove gitlab
